[package]
name = "yfinance-rs"
version = "0.0.1"
edition = "2024"
description = "Ergonomic Yahoo Finance client for Rust (history, streaming, profiles)."
license = "MIT"
repository = "https://github.com/gramistella/yfinance-rs"
build = "build.rs"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
reqwest = { version = "0.12.23", default-features = false, features = ["json", "rustls-tls", "gzip", "brotli", "deflate", "cookies"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
thiserror = "2.0.14"
url = "2.5.4"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
futures = "0.3.31"
tokio-tungstenite = { version = "0.23.1", features = ["rustls-tls-native-roots"] }
futures-util = "0.3.31"
prost = "0.12.6"
base64 = "0.22.1"

[dev-dependencies]
httpmock = "0.7.0"

[build-dependencies]
prost-build = "0.12.6"

[features]
test-mode = []
debug-dumps = []