# .github/workflows/publish.yml
name: Publish to crates.io

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Trigger on tags like v0.1.0, v1.2.3, v1.0.0-beta.1

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read # Give the job read-only permission to the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install just
        run: cargo install just

      # Ensure tests pass before publishing
      - name: Run offline tests
        run: just test-offline

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}